- title: Design and specification review
  image: assets/img/card-design.jpg
  image_position: 70% 30%
- title: Controls integration
  image: assets/img/card-controls.jpg
  image_position: 50% 50%
- title: Owner's representation
  image: assets/img/card-owners.jpg
  image_position: 40% 40%
- title: Sequences of operation
  image: assets/img/card-sequences.jpg
  image_position: 50% 50%
- title: Commissioning support
  image: assets/img/card-commissioning.jpg
  image_position: 55% 35%
- title: Alarms and graphics
  image: assets/img/card-alarms.jpg
  image_position: 50% 50%
